spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: DBDEMO
    password: admin123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  secret: MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=
  expiration: 86400000